<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nome_login</name>
   <tag></tag>
   <elementGuidId>759a5ba5-a843-4f9a-a97e-2abccb49143f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name-sign-up</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='name-sign-up']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1600fc8-eb91-4719-8806-48d1aff2c554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tell us what is your name</value>
      <webElementGuid>2818cc0a-669a-4bcb-9fb7-5b642dc468f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-sign-up</value>
      <webElementGuid>877872a3-1e3e-4977-9487-774c625300ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>7f6489d6-38b0-41d1-8e3e-a4641c5a5da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>19fe417a-df9b-458d-86f4-a4ad22cb7e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>a1f0d8ec-499c-48b2-be5e-70852d261392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-sign-up&quot;)</value>
      <webElementGuid>4a7163cc-565d-4e58-bc7e-536ae0c1f658</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='name-sign-up']</value>
      <webElementGuid>f4040da0-ad47-4b72-acb0-32f97fecb5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signupbox']/div/form/div[2]/div/input</value>
      <webElementGuid>9958c4f9-bed1-42ba-a8ea-bdff91f140d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c3a8c76c-0507-47a8-9b15-a72d78cbb9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tell us what is your name' and @id = 'name-sign-up' and @name = 'name' and @type = 'text']</value>
      <webElementGuid>59810014-e565-492a-af3f-b6dfcdaedf37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
