<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nome_usuario</name>
   <tag></tag>
   <elementGuidId>4dfbe926-0339-4922-9215-a2e4619eaa37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-sign-up</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-sign-up']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9fa5813c-8c8b-465d-a6b7-9578d223790f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>It's time to create a login</value>
      <webElementGuid>27c550a3-8e84-4c9c-b925-88a88fe1fda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-sign-up</value>
      <webElementGuid>96fbf861-9cbc-4a81-85fa-b8599f0d6f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>68f8c060-db1b-4bcc-bbb9-2c3f7b92d765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>968dad71-da92-4535-a34f-6d81d1cb01be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>d56f0d67-5955-4ec1-a085-b3ae890b7e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-sign-up&quot;)</value>
      <webElementGuid>34fc28e9-0617-460e-8f1e-8aba8825e28b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-sign-up']</value>
      <webElementGuid>c8fa7589-69cf-4747-9fb1-6b18e06ab9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signupbox']/div/form/div[3]/div/input</value>
      <webElementGuid>5553b83b-a515-4db0-87d0-1ff58ce2e4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>b4b20671-7c21-46bd-af14-df440e468a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = concat(&quot;It&quot; , &quot;'&quot; , &quot;s time to create a login&quot;) and @id = 'login-sign-up' and @name = 'login' and @type = 'text']</value>
      <webElementGuid>2d2b27b7-b553-4eb9-9746-8a760680efa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
