<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>senha</name>
   <tag></tag>
   <elementGuidId>9c22e18f-a1b5-424c-8a3c-71bccdbbde4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password-sign-up</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password-sign-up']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>149f33cd-891e-48ae-87c4-9dd03d772dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Take care, it need to be remembered</value>
      <webElementGuid>2966c25b-257c-4e01-9c9e-3ad842cc6454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-sign-up</value>
      <webElementGuid>682de58c-3bf1-485b-b41b-cad5418d7637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>205c0795-6249-4f0e-bd70-c3b09c3fbd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0e855736-5dbb-4bbf-999e-cefba15c5962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate</value>
      <webElementGuid>ccbe63ff-9c1c-40b5-ada2-2b6333f156f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-sign-up&quot;)</value>
      <webElementGuid>832aca7c-3f2c-4f76-8398-8f70d75d574f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password-sign-up']</value>
      <webElementGuid>98c5a1bb-04a1-430b-b033-355d475c4493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signupbox']/div/form/div[3]/div[2]/input</value>
      <webElementGuid>0d8f83e7-0d05-43b8-a61b-a4c582ad28bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4fb7d8d8-682e-42af-9773-94f141219500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Take care, it need to be remembered' and @id = 'password-sign-up' and @name = 'password' and @type = 'password']</value>
      <webElementGuid>1705e37b-e5bd-4d96-bd3e-e5cef8663918</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
