<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_signIn</name>
   <tag></tag>
   <elementGuidId>d41e8202-0e03-4a47-b3d2-c28f56316801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/nav/div/div/ul[1]/li/a[count(. | //*[@class = 'modal-trigger']) = count(//*[@class = 'modal-trigger'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-trigger</value>
      <webElementGuid>575b8af8-a92f-4404-9948-26d8255ae196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/nav/div/div/ul[1]/li/a</value>
      <webElementGuid>9a436e23-e78d-42b2-853b-f329ba9b129a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
